"""empty message

Revision ID: 3b79d0e0a5fb
Revises: a69b3283ee55
Create Date: 2025-04-02 16:57:27.447965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b79d0e0a5fb'
down_revision = 'a69b3283ee55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False, server_default='default_password'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
