"""Add created_datetime column to Notification

Revision ID: 4b4d6fae0375
Revises: 8afd925e8253
Create Date: 2025-04-01 20:14:51.728703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4d6fae0375'
down_revision = '8afd925e8253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_datetime', sa.DateTime(), nullable=False))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_datetime')

    # ### end Alembic commands ###
