"""empty message

Revision ID: a69b3283ee55
Revises: f125ebc9270d
Create Date: 2025-04-01 20:52:56.123626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69b3283ee55'
down_revision = 'f125ebc9270d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.drop_column('pasword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasword', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
