"""added password column to User

Revision ID: f125ebc9270d
Revises: 4b4d6fae0375
Create Date: 2025-04-01 20:44:52.532827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f125ebc9270d'
down_revision = '4b4d6fae0375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasword', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pasword')

    # ### end Alembic commands ###
